//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cargar_Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Estado_Solicitud
    {
        public int Id { get; set; }
        public int Estado { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public long id_registro_solicitud { get; set; }
        public string Usuario { get; set; }
    }
}
