//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cargar_Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro_Solicitudes
    {
        public int Id { get; set; }
        public string Placa { get; set; }
        public string Digito { get; set; }
        public string Tipo_Vehiculo { get; set; }
        public short Año_Fabricacion { get; set; }
        public string Modelo { get; set; }
        public string Color { get; set; }
        public string Marca { get; set; }
        public string Rut { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Comuna { get; set; }
        public string Telefono { get; set; }
        public string Mail { get; set; }
        public int Tramite { get; set; }
        public string Glosa { get; set; }
        public int Estado { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
