//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cargar_Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subdere
    {
        public int Id { get; set; }
        public string Institucion { get; set; }
        public string EstadoPago { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public Nullable<int> MontoOriginal { get; set; }
        public Nullable<int> MontoCuota { get; set; }
        public Nullable<int> MontoIpc { get; set; }
        public Nullable<int> MontoReajuste { get; set; }
        public Nullable<int> MontoInteres { get; set; }
        public Nullable<int> MontoPagar { get; set; }
        public Nullable<int> NumeroSerie { get; set; }
        public string CodigoVerificacion { get; set; }
        public Nullable<int> CodigoIra { get; set; }
        public string NombreIra { get; set; }
        public Nullable<int> CodigoTransaccion { get; set; }
        public string PagoDuplicado { get; set; }
        public string Rut { get; set; }
        public string Patente { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<int> NroSerieDocumento { get; set; }
        public Nullable<System.DateTime> FechaFactura { get; set; }
        public Nullable<System.DateTime> FechaEmisionHomologacion { get; set; }
        public Nullable<long> ValorNetoFactura { get; set; }
        public string DigitoVerificadorPatente { get; set; }
        public string CodigoSII { get; set; }
        public Nullable<int> Ano { get; set; }
        public Nullable<long> Tasacion { get; set; }
        public string Motor { get; set; }
        public string Chasis { get; set; }
        public string Color { get; set; }
        public Nullable<int> NroAsientos { get; set; }
        public Nullable<int> Tara { get; set; }
        public string NombrePropietario { get; set; }
        public string DomicilioPropietario { get; set; }
        public string ComunaPropietario { get; set; }
        public string TelefonoPropietario { get; set; }
        public string SelloVerde { get; set; }
        public Nullable<System.DateTime> FechaPlazoHomologacion { get; set; }
        public string Modelo { get; set; }
        public string Marca { get; set; }
        public string TipoVehiculo { get; set; }
        public Nullable<int> Cilindrada { get; set; }
        public string Combustible { get; set; }
        public string Transmision { get; set; }
        public string Equipamiento { get; set; }
        public Nullable<int> NroPuertas { get; set; }
        public string ZonaFranca { get; set; }
        public Nullable<int> Tonelaje { get; set; }
        public string Cuota { get; set; }
        public string PolizaSoap { get; set; }
        public string NombreAseguradora { get; set; }
        public string CertificadoRevisionTecnica { get; set; }
        public string CertificadoRevisionGases { get; set; }
        public string CodigoPlantaRevisionTecnica { get; set; }
        public string CodigoPlantaRevisionGases { get; set; }
        public string NombreContribuyente { get; set; }
        public string EmailContribuyente { get; set; }
    }
}
